### ISSUE TITLE
google/api/annotations.proto

### ISSUE THREAD

**Issue by tjiptomangun** [btlines/grpcexample#8]
I cannot compile your codes, 
It gives me
route_guide.proto: Import "google/api/annotations.proto" was not found or had errors

**Comment by Wei-1** [comment]
This question is answered in
https://github.com/grpc-ecosystem/grpc-gateway/issues/574#issuecomment-376018797
Caused by an environment variable
Suggest to close

**Comment by tjiptomangun** [comment]
Thank you @Wei-1  Thank you, sorry for late action. I just figure out how to close it
